export const settings = {
  resetToSelect: 'paste',
  rotationStep: 15,
  showValenceWarnings: true,
  atomColoring: true,
  showStereoFlags: true,
  stereoLabelStyle: 'Iupac',
  colorOfAbsoluteCenters: '#ff0000',
  colorOfAndCenters: '#0000cd',
  colorOfOrCenters: '#228b22',
  colorStereogenicCenters: 'LabelsOnly',
  autoFadeOfStereoLabels: true,
  absFlagLabel: 'ABS',
  andFlagLabel: 'AND Enantiomer',
  mixedFlagLabel: 'Mixed',
  ignoreChiralFlag: false,
  orFlagLabel: 'OR Enantiomer',
  font: '30px Arial',
  fontsz: 13,
  fontszUnit: 'px',
  fontszsub: 13,
  fontszsubUnit: 'px',
  carbonExplicitly: false,
  showCharge: true,
  showValence: true,
  showHydrogenLabels: 'Terminal and Hetero',
  aromaticCircle: true,
  doubleBondWidth: 6,
  doubleBondWidthUnit: 'px',
  bondThickness: 2,
  bondThicknessUnit: 'px',
  stereoBondWidth: 6,
  stereoBondWidthUnit: 'px',
  bondLength: 2.1,
  bondLengthUnit: 'px',
  reactionComponentMarginSize: 2.3,
  reactionComponentMarginSizeUnit: 'px',
  hashSpacing: 2.2,
  hashSpacingUnit: 'px',
  imageResolution: '72',
  'dearomatize-on-load': false,
  'smart-layout': true,
  'ignore-stereochemistry-errors': true,
  'mass-skip-error-on-pseudoatoms': false,
  'gross-formula-add-rsites': true,
  'gross-formula-add-isotopes': true,
  showAtomIds: false,
  showBondIds: false,
  showHalfBondIds: false,
  showLoopIds: false,
  miewMode: 'LN',
  miewTheme: 'light',
  miewAtomLabel: 'bright',
  init: true
}
